# Generated by Django 5.0.14 on 2026-09-10 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón social')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('unidad_medida', models.CharField(choices=[('TONELADA', 'Tonelada')], default='TONELADA', max_length=10, verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón social')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'transportista',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('tipo_titularidad', models.CharField(choices=[('PROPIO', 'Propio'), ('EXTERNO', 'Externo')], max_length=10, verbose_name='Titularidad')),
                ('capacidad_tn', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Capacidad (tn)')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='catalogo.transportista', verbose_name='Transportista')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
                'ordering': ['placa'],
                'indexes': [models.Index(fields=['tipo_titularidad'], name='idx_vehiculo_titularidad')],
            },
        ),
    ]
