# Generated by Django 5.0.14 on 2026-09-12 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorCorrelativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('ultimo_valor', models.PositiveIntegerField(default=0, verbose_name='Último valor emitido')),
            ],
            options={
                'verbose_name': 'Contador de correlativo',
                'verbose_name_plural': 'Contadores de correlativo',
                'db_table': 'contador_correlativo_ingreso',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Correlativo')),
                ('uuid_local', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Identificador local')),
                ('fecha_pesaje', models.DateField(verbose_name='Fecha de pesaje')),
                ('hora_pesaje', models.TimeField(verbose_name='Hora de pesaje')),
                ('hora_registro', models.DateTimeField(editable=False, verbose_name='Hora de registro')),
                ('hora_sincronizacion', models.DateTimeField(blank=True, null=True, verbose_name='Hora de sincronización')),
                ('peso_bruto_tn', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso bruto (tn)')),
                ('tara_tn', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tara (tn)')),
                ('peso_neto_tn', models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Peso neto (tn)')),
                ('numero_ticket', models.CharField(max_length=20, verbose_name='Número de ticket')),
                ('capturado_offline', models.BooleanField(default=False, verbose_name='Capturado sin conexión')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=10, verbose_name='Estado')),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de anulación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='catalogo.producto', verbose_name='Producto')),
                ('usuario_registro', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='catalogo.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'ingreso',
                'ordering': ['-fecha_pesaje', '-hora_pesaje'],
                'indexes': [models.Index(fields=['fecha_pesaje', 'producto'], name='idx_ingreso_fecha_producto')],
            },
        ),
        migrations.AddConstraint(
            model_name='ingreso',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'REGISTRADO')), fields=('numero_ticket',), name='uq_ingreso_ticket_no_anulado'),
        ),
        migrations.AddConstraint(
            model_name='ingreso',
            constraint=models.CheckConstraint(check=models.Q(('tara_tn__lt', models.F('peso_bruto_tn'))), name='ck_ingreso_tara_menor_bruto'),
        ),
        migrations.AddConstraint(
            model_name='ingreso',
            constraint=models.CheckConstraint(check=models.Q(('peso_bruto_tn__gt', 0), ('tara_tn__gt', 0)), name='ck_ingreso_pesos_positivos'),
        ),
    ]
