# Generated by Django 5.0.14 on 2026-09-17 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorCorrelativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('ultimo_valor', models.PositiveIntegerField(default=0, verbose_name='Último valor emitido')),
            ],
            options={
                'verbose_name': 'Contador de correlativo de salidas',
                'verbose_name_plural': 'Contadores de correlativo de salidas',
                'db_table': 'contador_correlativo_salida',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Correlativo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_registro', models.DateTimeField(editable=False, verbose_name='Hora de registro')),
                ('tipo_movimiento', models.CharField(choices=[('VENTA', 'Venta'), ('TRASLADO_INTERNO', 'Traslado interno'), ('MERMA', 'Merma')], max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad_tn', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad (tn)')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=10, verbose_name='Estado')),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de anulación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='catalogo.cliente', verbose_name='Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='catalogo.producto', verbose_name='Producto')),
                ('usuario_registro', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'db_table': 'salida',
                'ordering': ['-fecha', '-hora_registro'],
                'indexes': [models.Index(fields=['fecha', 'producto'], name='idx_salida_fecha_producto')],
            },
        ),
        migrations.AddConstraint(
            model_name='salida',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_tn__gt', 0)), name='ck_salida_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='salida',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tipo_movimiento', 'VENTA'), _negated=True), ('cliente__isnull', False), _connector='OR'), name='ck_salida_venta_con_cliente'),
        ),
        migrations.AddConstraint(
            model_name='salida',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tipo_movimiento', 'MERMA'), _negated=True), models.Q(('motivo__isnull', False), models.Q(('motivo', ''), _negated=True)), _connector='OR'), name='ck_salida_merma_con_motivo'),
        ),
    ]
